# -*- coding: utf-8 -*-
"""1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/chethan1996/BEFinalProject/blob/master/Face_Emotion_Detection/1.ipynb
"""

import cv2
import os

cam = cv2.VideoCapture(0)
cam.set(3, 640) # set video width
cam.set(4, 480) # set video height

face_detector = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
eye_detector  = cv2.CascadeClassifier('haarcascade_eye_tree_eyeglasses.xml')
nose_detector = cv2.CascadeClassifier('haarcascade_mcs_nose.xml')
half_face_detector = cv2.CascadeClassifier('haarcascade_profileface.xml')

"""### Next cell will take few seconds ! Be prepared taking photos!
### Remmember change your facial expression a little bit sometimes!
"""

# For each person, enter one numeric face id
face_id = input('\n Enter User ID and Press <Enter> ==>  ')

print("\n [INFO] Initializing Face Capture. Look the camera and wait ...")
print("\n Tip: Give different Poses during Face Capture")
# Initialize individual sampling face count
count = 0

while(True):

    ret, img = cam.read()
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    faces = face_detector.detectMultiScale(gray, 1.3, 5)

    for (x,y,w,h) in faces:

        cv2.rectangle(img, (x,y), (x+w,y+h), (255,0,0), 2)     
        count += 1
        eye = eye_detector.detectMultiScale(gray, 1.3, 5)
        nose = nose_detector.detectMultiScale(gray, 1.3, 5)
        half_face = half_face_detector.detectMultiScale(gray, 1.3, 5)
        # Save the captured image into the datasets folder
        cv2.imwrite("dataset/User." + str(face_id) + '.' + str(count) + ".jpg", gray[y:y+h,x:x+w])

        cv2.imshow('image', img)

    k = cv2.waitKey(100) & 0xff # Press 'ESC' for exiting video
    if k == 27:
        break
    elif count >= 100: # Take 80 face sample and stop video
         break

# Do a bit of cleanup
print("\n [INFO] Exiting Program and cleanup stuff")
cam.release()
cv2.destroyAllWindows()

"""## Now you can go to 'dataset' folder see your selfies!"""

